#ifndef QXTSIGNALWAITER_GLOBAL_H
#define QXTSIGNALWAITER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(QXTSIGNAL_LIBRARY)
#  define QXTSIGNALSHARED_EXPORT Q_DECL_EXPORT
#else
#  define QXTSIGNALSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // QXTSIGNALWAITER_GLOBAL_H
