#ifndef QXTSIGNALWAITER_GLOBAL_H
#define QXTSIGNALWAITER_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef QXTSIGNAL_STATIC
#  define QXTSIGNALSHARED_EXPORT
#else
#  ifdef QXTSIGNAL_LIBRARY
#    define QXTSIGNALSHARED_EXPORT Q_DECL_EXPORT
#  else
#    define QXTSIGNALSHARED_EXPORT Q_DECL_IMPORT
#  endif
#endif

#endif // QXTSIGNALWAITER_GLOBAL_H
